### ISSUE TITLE
The app crashes when you use `θ = 180 degrees`.

### ISSUE THREAD

**Issue by Mw3y** [epfl-physics/spinning-top#6]
```
Uncaught RuntimeError: float unrepresentable in integer range
    at SpinningTop.wasm:0xda999e
    at SpinningTop.wasm:0x113056e
    at SpinningTop.wasm:0x113106f
    at SpinningTop.wasm:0x113ea0b
    at SpinningTop.wasm:0xd831e8
    at SpinningTop.wasm:0x11d8f94
    at SpinningTop.wasm:0x11d87b9
    at SpinningTop.wasm:0x11dad83
    at SpinningTop.wasm:0x109915a
    at SpinningTop.wasm:0x1206f73
    at Object.dynCall_iiiii (SpinningTop.framework.js:2:470896)
    at invoke_iiiii (SpinningTop.framework.js:2:334882)
    at SpinningTop.wasm:0x10375c8
    at SpinningTop.wasm:0x101ec48
    at SpinningTop.wasm:0x1b2558
    at SpinningTop.wasm:0x1b2228
    at SpinningTop.wasm:0x3e3ef4
    at SpinningTop.wasm:0x3e2a08
    at SpinningTop.wasm:0x51cb32
    at SpinningTop.wasm:0x51c84b
    at SpinningTop.wasm:0x412590
    at SpinningTop.wasm:0x3ed3c5
    at SpinningTop.wasm:0x3ed3da
    at SpinningTop.wasm:0x3ecf5f
    at SpinningTop.wasm:0x3eb1fa
    at SpinningTop.wasm:0x1207252
    at Object.dynCall_v (SpinningTop.framework.js:2:480125)
    at browserIterationFunc (SpinningTop.framework.js:2:171816)
    at Object.runIter (SpinningTop.framework.js:2:174877)
    at Browser_mainLoop_runner (SpinningTop.framework.js:2:173339)
```

## Steps to reproduce:
1. Launch the simulation with the default parameters.
2. Set θ to 180 degrees.
3. Relaunch the simulation.

Thanks for making this amazing program! Very interesting.

**Comment by austinpeel** [comment]
Thanks for pointing this out!

Although I wasn't able to reproduce the error myself in Unity or in the various browsers I tested, I'm pretty sure I know where the bug was coming from. There was a division by zero in the numerical solver when theta = 180 deg. I've now accounted for this, and the issue should be solved. Please let me know if it still causes trouble for you.

**Comment by Mw3y** [comment]
> Thanks for pointing this out!
> 
> 
> 
> Although I wasn't able to reproduce the error myself in Unity or in the various browsers I tested, I'm pretty sure I know where the bug was coming from. There was a division by zero in the numerical solver when theta = 180 deg. I've now accounted for this, and the issue should be solved. Please let me know if it still causes trouble for you.

Alright, thank you!
